import { Category } from './types'

export const addresses: Category = {
	id: 'addresses',
	label: 'Addresses',
	type: 'category',
	isAvailable: true,
	children: [
		{
			id: 'address-activity',
			label: 'Address Activity',
			type: 'group',
			isAvailable: true,
			children: [
				{
					id: 'active-addresses-count',
					label: 'Active Addresses',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'sending-addresses-count',
					label: 'Sending Addresses',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'receiving-addresses-count',
					label: 'Receiving Addresses',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'Active-address-momentum',
					label: 'Active Address Momentum',
					type: 'indicator',
					isAvailable: true,
				},
			],
		},
		{
			id: 'address-growth',
			label: 'Address Growth',
			type: 'group',
			isAvailable: true,
			children: [
				{
					id: 'new-addresses-count',
					label: 'New Addresses',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'total-addresses-count',
					label: 'Total Addresses',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'new-address-momentum',
					label: 'New Address Momentum',
					type: 'indicator',
					isAvailable: true,
				},
			],
		},
		{
			id: 'address-by-balance',
			label: 'Address by Balance',
			type: 'group',
			isAvailable: true,
			children: [
				{
					id: 'address-nonZeroCount',
					label: 'Address with Non-Zero Balance',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'address-min1Count',
					label: 'Address with Balance ≥ 1 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'address-min10Count',
					label: 'Address with Balance ≥ 10 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'address-min100Count',
					label: 'Address with Balance ≥ 100 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'address-min500Count',
					label: 'Address with Balance ≥ 500 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'address-min1kCount',
					label: 'Address with Balance ≥ 1,000 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'address-min5kCount',
					label: 'Address with Balance ≥ 5,000 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'address-min10kCount',
					label: 'Address with Balance ≥ 10,000 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'address-min100kCount',
					label: 'Address with Balance ≥ 100,000 ICP',
					type: 'indicator',
					isAvailable: true,
				},
			],
		},
		{
			id: 'address-supply-distribution',
			label: 'Address Supply Distribution',
			type: 'group',
			isAvailable: true,
			children: [
				{
					id: 'plankton-netPosChange',
					label: 'Plankton net position change : Address < 1 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'shrimp-netPosChange',
					label: 'Shrimp net position change : Address 1 - 10 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'crab-netPosChange',
					label: 'Crab net position change : Address 10 - 100 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'octopus-netPosChange',
					label: 'Octopus net position change : Address 100 - 500 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'fish-netPosChange',
					label: 'Fish net position change : Address 500 - 1,000 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'dolphin-netPosChange',
					label: 'Dolphin net position change : Address 1,000 - 5,000 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'shark-netPosChange',
					label: 'Shark net position change : Address 5,000 - 10,000 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'whale-netPosChange',
					label: 'Whale net position change : Address 10,000 - 100,000 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'humpback-netPosChange',
					label: 'Humpback net position change : Address > 100,000 ICP',
					type: 'indicator',
					isAvailable: true,
				},
			],
		},
		{
			id: 'address-supply-bands',
			label: 'Address Supply Bands',
			type: 'group',
			isAvailable: true,
			children: [
				{
					id: 'address-supply-balance-less1',
					label: 'Supply held by addresses with balance < 1 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'address-supply-balance-1-10',
					label: 'Supply held by addresses with balance 1 - 10 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'address-supply-balance-10-100',
					label: 'Supply held by addresses with balance 10 - 100 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'address-supply-balance-100-500',
					label: 'Supply held by addresses with balance 100 - 500 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'address-supply-balance-500-1k',
					label: 'Supply held by addresses with balance 500 - 1,000 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'address-supply-balance-1k-5k',
					label: 'Supply held by addresses with balance 1,000 - 5,000 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'address-supply-balance-5k-10k',
					label: 'Supply held by addresses with balance 5,000 - 10,000 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'address-supply-balance-10k-100k',
					label: 'Supply held by addresses with balance 10,000 - 100,000 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'address-supply-balance-more100k',
					label: 'Supply held by addresses with balance > 100,000 ICP',
					type: 'indicator',
					isAvailable: true,
				},
			],
		},
		{
			id: 'address-count',
			label: 'Address Count Distribution',
			type: 'group',
			isAvailable: true,
			children: [
				{
					id: 'plankton-count',
					label: 'Plankton address count : < 1 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'shrimp-count',
					label: 'Shrimp address count : 1 - 10 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'crab-count',
					label: 'Crab address count : 10 - 100 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'octopus-count',
					label: 'Octopus address count : 100 - 500 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'fish-count',
					label: 'Fish address count : 500 - 1,000 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'dolphin-count',
					label: 'Dolphin address count : 1,000 - 5,000 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'shark-count',
					label: 'Shark address count : 5,000 - 10,000 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'whale-count',
					label: 'Whale address count : 10,000 - 100,000 ICP',
					type: 'indicator',
					isAvailable: true,
				},
				{
					id: 'humpback-count',
					label: 'Humpback address count : > 100,000 ICP',
					type: 'indicator',
					isAvailable: true,
				},
			],
		},
	],
}
