import { TreeViewBaseItem } from '@mui/x-tree-view'
import { ExtendedTreeItemProps } from './TreeView.type'

export const constants: TreeViewBaseItem<ExtendedTreeItemProps>[] = [
	{
		id: 'address-supply-distribution',
		label: 'Address Supply Distribution',
		type: 'category',
		isAvailable: true,
		children: [
			{
				id: 'plankton-netPosChange',
				label: 'Plankton net position change : Address < 1 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'shrimp-netPosChange',
				label: 'Shrimp net position change : Address 1 - 10 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'crab-netPosChange',
				label: 'Crab net position change : Address 10 - 100 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'octopus-netPosChange',
				label: 'Octopus net position change : Address 100 - 500 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'fish-netPosChange',
				label: 'Fish net position change : Address 500 - 1,000 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'dolphin-netPosChange',
				label: 'Dolphin net position change : Address 1,000 - 5,000 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'shark-netPosChange',
				label: 'Shark net position change : Address 5,000 - 10,000 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'whale-netPosChange',
				label: 'Whale net position change : Address 10,000 - 100,000 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'humpback-netPosChange',
				label: 'Humpback net position change : Address > 100,000 ICP',
				type: 'indicator',
				isAvailable: true,
			},
		],
	},
	{
		id: 'address-supply-bands',
		label: 'Address Supply Bands',
		type: 'category',
		isAvailable: false,
		children: [
			{
				id: 'address-supply-balance-less1',
				label: 'Supply held by addresses with balance < 1 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'address-supply-balance-1-10',
				label: 'Supply held by addresses with balance 1 - 10 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'address-supply-balance-10-100',
				label: 'Supply held by addresses with balance 10 - 100 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'address-supply-balance-100-500',
				label: 'Supply held by addresses with balance 100 - 500 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'address-supply-balance-500-1k',
				label: 'Supply held by addresses with balance 500 - 1,000 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'address-supply-balance-1k-5k',
				label: 'Supply held by addresses with balance 1,000 - 5,000 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'address-supply-balance-5k-10k',
				label: 'Supply held by addresses with balance 5,000 - 10,000 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'address-supply-balance-10k-100k',
				label: 'Supply held by addresses with balance 10,000 - 100,000 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'address-supply-balance-more100k',
				label: 'Supply held by addresses with balance > 100,000 ICP',
				type: 'indicator',
				isAvailable: true,
			},
		],
	},
	{
		id: 'address-count',
		label: 'Address Count Distribution',
		type: 'category',
		isAvailable: true,
		children: [
			{
				id: 'plankton-count',
				label: 'Plankton address count : < 1 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'shrimp-count',
				label: 'Shrimp address count : 1 - 10 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'crab-count',
				label: 'Crab address count : 10 - 100 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'octopus-count',
				label: 'Octopus address count : 100 - 500 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'fish-count',
				label: 'Fish address count : 500 - 1,000 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'dolphin-count',
				label: 'Dolphin address count : 1,000 - 5,000 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'shark-count',
				label: 'Shark address count : 5,000 - 10,000 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'whale-count',
				label: 'Whale address count : 10,000 - 100,000 ICP',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'humpback-count',
				label: 'Humpback address count : > 100,000 ICP',
				type: 'indicator',
				isAvailable: true,
			},
		],
	},
	{
		id: 'exchange-activity',
		label: 'Exchange Activity',
		type: 'category',
		isAvailable: true,
		children: [
			{
				id: 'exchange-netflow-volume',
				label: 'Exchange Netflow Volume',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'exchange-inflow-volume',
				label: 'Exchange Inflow Volume',
				type: 'indicator',
				isAvailable: true,
			},
			{
				id: 'exchange-outflow-volume',
				label: 'Exchange Outflow Volume',
				type: 'indicator',
				isAvailable: true,
			},
		],
	},
	{
		id: 'profit-loss',
		label: 'Profit/Loss',
		type: 'category',
		isAvailable: false,
		children: [
			// {
			//   id: '4.1',
			//   label: '...',
			//   type: 'indicator',
			//   isAvailable: true,
			// },
			// {
			//   id: '4.2',
			//   label: '...',
			//   type: 'indicator',
			//   isAvailable: true,
			// },
			// {
			//   id: '4.3',
			//   label: '...',
			//   type: 'indicator',
			//   isAvailable: true,
			// },
			// {
			//   id: '4.4',
			//   label: '...',
			//   type: 'indicator',
			//   isAvailable: true,
			// },
			// {
			//   id: '4.5',
			//   label: '...',
			//   type: 'indicator',
			//   isAvailable: true,
			// },
		],
	},
]
